package enums;
/**
 * This Enum is used to describe status of an order in the system.
 * @author Omri Shalev
 */
public enum OrderStatus {
	PENDING("PENDING",0),
	APPROVE("APPROVE",1),
	CANCEL("CANCEL",2),
	ARRIVED("ARRIVED",3),
	TAKEAWAY("TAKEAWAY",4),
	
	
	PENDING_WITH_DELIVERY("PENDING_WITH_DELIVERY",5),
	APPROVE_WITH_DELIVERY("APPROVE_WITH_DELIVERY",6),

	CANCEL_WITH_DELIVERY("CANCEL_WITH_DELIVERY",7), 
	
	CANCEL_ORDER_BY_CUSTOMER("CANCEL_ORDER_BY_CUSTOMER",8),
	APPROVE_ORDER_CANCELATION("APPROVE_ORDER_CANCELATIONL",9),
	DECLINE_ORDER_CANCELATION("DECLINE_ORDER_CANCELATION",10),
	
	
	CANCEL_ORDER_DELIVERY_BY_CUSTOMER("CANCEL_ORDER_DELIVERY_BY_CUSTOMER",11),
	APPROVE_ORDER_DELIVERY_CANCELATION("APPROVE_ORDER_DELIVERY_CANCELATION",12),
	DECLINE_ORDER_DELIVERY_CANCELATION("DECLINE_ORDER_DELIVERY_CANCELATION",13), 
	PENDING_WITH_IMIDATE_DELIVERY("PENDING_WITH_IMIDATE_DELIVERY",14), 
	APPROVE_WITH_IMIDATE_DELIVERY("APPROVE_WITH_IMIDATE_DELIVERY",15);


	


	private OrderStatus(String string, int i) {
	}
}
